-- Phase 1 BetMind AI schema (secure-by-default)

-- Extensions
create extension if not exists pgcrypto;

-- Roles enum + user roles table (security requirement)
do $$ begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum ('admin', 'moderator', 'user');
  end if;
end $$;

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

alter table public.user_roles enable row level security;

create or replace function public.has_role(_user_id uuid, _role public.app_role)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = _user_id
      and role = _role
  )
$$;

-- Profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Competition/team base
create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  logo_url text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Dedicated cache table for external logos
create table if not exists public.team_logos (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  provider text not null,
  logo_url text not null,
  fetched_at timestamptz not null default now(),
  unique (team_id, provider)
);

-- Historical matches
create table if not exists public.matches_history (
  id uuid primary key default gen_random_uuid(),
  external_match_id text unique,
  match_date timestamptz not null,
  league text not null,
  season text,
  home_team_id uuid not null references public.teams(id),
  away_team_id uuid not null references public.teams(id),
  home_score int,
  away_score int,
  created_at timestamptz not null default now()
);

-- Historical events
create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches_history(id) on delete cascade,
  minute int,
  team_id uuid references public.teams(id),
  type text not null check (type in ('goal','foul','corner','card','substitution','shot','other')),
  created_at timestamptz not null default now()
);

-- Match stats aggregate
create table if not exists public.match_stats (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null unique references public.matches_history(id) on delete cascade,
  goals_home int not null default 0,
  goals_away int not null default 0,
  corners_home int not null default 0,
  corners_away int not null default 0,
  fouls_home int not null default 0,
  fouls_away int not null default 0,
  cards_home int not null default 0,
  cards_away int not null default 0,
  updated_at timestamptz not null default now()
);

-- Team rolling stats
create table if not exists public.team_stats (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null unique references public.teams(id) on delete cascade,
  avg_goals numeric(6,3) not null default 0,
  avg_corners numeric(6,3) not null default 0,
  avg_cards numeric(6,3) not null default 0,
  win_rate numeric(6,3) not null default 0,
  updated_at timestamptz not null default now()
);

-- Live matches
create table if not exists public.matches_live (
  id uuid primary key default gen_random_uuid(),
  external_match_id text unique,
  league text not null,
  home_team_id uuid not null references public.teams(id),
  away_team_id uuid not null references public.teams(id),
  home_score int not null default 0,
  away_score int not null default 0,
  minute int not null default 0,
  status text not null default 'live',
  odds_home numeric(10,3),
  odds_draw numeric(10,3),
  odds_away numeric(10,3),
  is_hot boolean not null default false,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Alerts generated by engine
create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  match_live_id uuid not null references public.matches_live(id) on delete cascade,
  type text not null check (type in ('goal_imminent','corners_sequence','card_risk','comeback','final_minutes','value_odds')),
  message text not null,
  score int not null check (score between 0 and 100),
  created_at timestamptz not null default now()
);

-- Model predictions for live matches
create table if not exists public.match_predictions (
  id uuid primary key default gen_random_uuid(),
  match_live_id uuid not null unique references public.matches_live(id) on delete cascade,
  win_home_prob numeric(6,5) not null check (win_home_prob between 0 and 1),
  win_draw_prob numeric(6,5) not null check (win_draw_prob between 0 and 1),
  win_away_prob numeric(6,5) not null check (win_away_prob between 0 and 1),
  goal_prob numeric(6,5) not null check (goal_prob between 0 and 1),
  corner_prob numeric(6,5) not null check (corner_prob between 0 and 1),
  card_prob numeric(6,5) not null check (card_prob between 0 and 1),
  confidence numeric(6,5) not null check (confidence between 0 and 1),
  updated_at timestamptz not null default now()
);

-- User-specific alert preferences
create table if not exists public.user_alert_preferences (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  min_score int not null default 60 check (min_score between 0 and 100),
  goal_imminent_enabled boolean not null default true,
  corners_enabled boolean not null default true,
  card_enabled boolean not null default true,
  comeback_enabled boolean not null default true,
  final_minutes_enabled boolean not null default true,
  value_odds_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

-- Updated at helper
create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Auto profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do nothing;

  insert into public.user_alert_preferences (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  insert into public.user_roles (user_id, role)
  values (new.id, 'user')
  on conflict (user_id, role) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Update triggers
create trigger update_profiles_updated_at
before update on public.profiles
for each row execute function public.update_updated_at_column();

create trigger update_teams_updated_at
before update on public.teams
for each row execute function public.update_updated_at_column();

create trigger update_match_stats_updated_at
before update on public.match_stats
for each row execute function public.update_updated_at_column();

create trigger update_team_stats_updated_at
before update on public.team_stats
for each row execute function public.update_updated_at_column();

create trigger update_matches_live_updated_at
before update on public.matches_live
for each row execute function public.update_updated_at_column();

create trigger update_match_predictions_updated_at
before update on public.match_predictions
for each row execute function public.update_updated_at_column();

create trigger update_user_alert_preferences_updated_at
before update on public.user_alert_preferences
for each row execute function public.update_updated_at_column();

-- RLS
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.team_logos enable row level security;
alter table public.matches_history enable row level security;
alter table public.events enable row level security;
alter table public.match_stats enable row level security;
alter table public.team_stats enable row level security;
alter table public.matches_live enable row level security;
alter table public.alerts enable row level security;
alter table public.match_predictions enable row level security;
alter table public.user_alert_preferences enable row level security;

-- Profiles policies
create policy "Users can view their own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Users can insert their own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

-- Read-only domain data for authenticated users
create policy "Authenticated can read teams"
on public.teams
for select
to authenticated
using (true);

create policy "Authenticated can read team logos"
on public.team_logos
for select
to authenticated
using (true);

create policy "Authenticated can read matches history"
on public.matches_history
for select
to authenticated
using (true);

create policy "Authenticated can read events"
on public.events
for select
to authenticated
using (true);

create policy "Authenticated can read match stats"
on public.match_stats
for select
to authenticated
using (true);

create policy "Authenticated can read team stats"
on public.team_stats
for select
to authenticated
using (true);

create policy "Authenticated can read live matches"
on public.matches_live
for select
to authenticated
using (true);

create policy "Authenticated can read alerts"
on public.alerts
for select
to authenticated
using (true);

create policy "Authenticated can read predictions"
on public.match_predictions
for select
to authenticated
using (true);

-- User-owned preferences
create policy "Users can view own alert preferences"
on public.user_alert_preferences
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own alert preferences"
on public.user_alert_preferences
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own alert preferences"
on public.user_alert_preferences
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- user_roles policies
create policy "Users can view their own roles"
on public.user_roles
for select
to authenticated
using (auth.uid() = user_id);

-- Admin write policies
create policy "Admins can manage teams"
on public.teams
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage team logos"
on public.team_logos
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage matches history"
on public.matches_history
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage events"
on public.events
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage match stats"
on public.match_stats
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage team stats"
on public.team_stats
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage live matches"
on public.matches_live
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage alerts"
on public.alerts
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage predictions"
on public.match_predictions
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "Admins can manage user roles"
on public.user_roles
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

-- Indexes
create index if not exists idx_events_match_id on public.events(match_id);
create index if not exists idx_events_type on public.events(type);
create index if not exists idx_matches_live_updated_at on public.matches_live(updated_at desc);
create index if not exists idx_alerts_match_live_id on public.alerts(match_live_id);
create index if not exists idx_alerts_score on public.alerts(score desc);
create index if not exists idx_matches_history_date on public.matches_history(match_date desc);
create index if not exists idx_teams_name on public.teams(name);
create index if not exists idx_team_logos_team_id on public.team_logos(team_id);
create index if not exists idx_user_roles_user_id on public.user_roles(user_id);
create index if not exists idx_user_alert_preferences_user_id on public.user_alert_preferences(user_id);